create table if not exists public.employees (
    id bigint generated by default as identity primary key,
    employee_code varchar(20) not null unique,
    name varchar(100) not null,
    email varchar(150) not null unique,
    department varchar(80) not null,
    role varchar(100) not null,
    status varchar(20) not null default 'Active'
        check (status in ('Active', 'On Leave', 'Inactive')),
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_employees_name on public.employees (name);
create index if not exists ix_employees_department on public.employees (department);
create index if not exists ix_employees_status on public.employees (status);
